/**
 * Reading a real PDF, not a string somebody typed to make a test pass.
 *
 * `test/fixtures/quote.pdf` is generated by `make-quote.mjs` with the same
 * jsPDF this build already ships, so what is parsed here has a genuine text
 * layer, a genuine font and genuine coordinates. A fixture made of hand-written
 * `TextCell` objects would pass whatever grouping rule it was written against,
 * which is the opposite of a test.
 *
 * The grouping itself is pinned separately with hand-built cells, because that
 * is where the rules live and a file cannot express "these two runs are 1pt
 * apart" on purpose.
 *
 * pdf.js warns here that `standardFontDataUrl` is unset. It is unset on purpose:
 * that data exists to DRAW the standard fonts, this reads text and never draws a
 * glyph, and supplying it would mean shipping a megabyte of font files. The
 * warning is noise, and these tests passing on their exact strings is the proof.
 */
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { cellsToRows, readPdf, type TextCell } from '@/lib/intake/pdf'

/**
 * pdf.js's Node build, which the browser never loads.
 *
 * `readPdf` takes the loader as an argument for exactly this: the shipping path
 * uses the browser build with a bundled worker, and the test uses the legacy
 * build with its worker named as a file. One parser, two ways in.
 */
const nodePdfjs = async () => {
  const mod = await import('pdfjs-dist/legacy/build/pdf.mjs')
  const m = mod as unknown as { GlobalWorkerOptions: { workerSrc: string } }
  m.GlobalWorkerOptions.workerSrc =
    new URL('../node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs', import.meta.url).href
  return mod as never
}

const fixture = () => {
  const b = readFileSync(new URL('./fixtures/quote.pdf', import.meta.url))
  return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) as ArrayBuffer
}

describe('a quotation that arrived as a PDF', () => {
  it('comes back as rows, in the order a person reads them', async () => {
    const { rows, pages, scanned } = await readPdf(fixture(), nodePdfjs)

    expect(pages).toBe(1)
    // a text layer, so nothing is sent to the OCR path
    expect(scanned).toEqual([])
    // the letterhead is first because the page is read top-down, not bottom-up.
    // If the y-flip is ever dropped this is the test that fails, and it fails
    // loudly rather than quietly producing an upside-down table.
    expect(rows[0][0]).toMatch(/SHAH METALS/i)
    expect(rows[rows.length - 1].join(' ')).toMatch(/^Terms:/i)
  })

  it('keeps each line of the table whole, with its rate on it', async () => {
    const { rows } = await readPdf(fixture(), nodePdfjs)
    const crca = rows.find((r) => r[0].startsWith('C.R.C.A.'))

    expect(crca).toBeDefined()
    // description, qty, unit, rate, amount — the supplier's own column order,
    // which is not this build's and is not meant to be
    expect(crca).toEqual([
      'C.R.C.A. SHEET 1.2MM 1250 WIDE (PRIME)', '12', 'MT', '62,800.00', '7,53,600.00',
    ])
  })

  it('finds every priced line on the document', async () => {
    const { rows } = await readPdf(fixture(), nodePdfjs)
    // five columns and a rate that parses: the shape a priced line has
    const priced = rows.filter((r) => r.length === 5 && /^[\d,]+\.\d\d$/.test(r[3]))
    expect(priced).toHaveLength(6)
  })

  it('reads the header a person would need to file it', async () => {
    const { rows } = await readPdf(fixture(), nodePdfjs)
    const flat = rows.map((r) => r.join(' ')).join('\n')
    expect(flat).toMatch(/SMA\/Q\/2026\/1184/)
    expect(flat).toMatch(/Valid until: 15\/10\/2026/)
  })
})

/* ------------------------------------------------------- the grouping rules -- */

const cell = (s: string, x: number, y: number, w = s.length * 5, h = 9): TextCell =>
  ({ s, x, y, w, h })

describe('runs of text back into rows', () => {
  it('treats a shared baseline as one row, within half a glyph height', () => {
    // 3pt apart at 9pt type is the same line — a slightly larger figure in one
    // column must not start a row of its own
    const rows = cellsToRows([cell('Sheet', 48, 100), cell('62,800', 300, 103)])
    expect(rows).toEqual([['Sheet', '62,800']])
  })

  it('and a real line break as a new one', () => {
    const rows = cellsToRows([cell('Sheet', 48, 100), cell('Tube', 48, 120)])
    expect(rows).toEqual([['Sheet'], ['Tube']])
  })

  it('joins runs a PDF split mid-phrase, and keeps the space', () => {
    /*
     * A PDF has no spaces — a gap is a move instruction. So "CRCA SHEET" can
     * arrive as two runs, and putting them back together is the whole reason
     * this function exists rather than a join on the raw items.
     */
    const rows = cellsToRows([cell('CRCA', 48, 100, 24), cell('SHEET', 74, 100, 30)])
    expect(rows).toEqual([['CRCA SHEET']])
  })

  it('but keeps a column break apart', () => {
    const rows = cellsToRows([cell('CRCA SHEET', 48, 100, 60), cell('62,800', 300, 100)])
    expect(rows).toEqual([['CRCA SHEET', '62,800']])
  })

  it('drops runs that are only whitespace', () => {
    expect(cellsToRows([cell(' ', 48, 100), cell('Sheet', 60, 100, 5)])).toEqual([['Sheet']])
  })

  it('has nothing to say about an empty page', () => {
    expect(cellsToRows([])).toEqual([])
  })

  it('joins words a reader reports one at a time, which is how OCR reports them', () => {
    /*
     * A PDF hands over phrases; OCR hands over words with a real space between
     * each. A threshold tight enough for the first leaves every word in a
     * column of its own — which turned a letterhead into a priced line and a
     * description into whichever of its words was longest, until a photograph
     * was actually put through it.
     */
    const word = (s: string, x: number) => cell(s, x, 100, s.length * 22, 40)
    expect(cellsToRows([
      word('CRCA', 100), word('SHEET', 210), word('1.2MM', 350),
      word('12', 835), word('MT', 990),
    ])).toEqual([['CRCA SHEET 1.2MM', '12', 'MT']])
  })

  it('follows a baseline that drifts, because a photographed page is never square', () => {
    /*
     * A page held at a degree and a half drifts thirty pixels across a wide
     * sheet — twice any sensible same-line tolerance. Measured from the row's
     * first cell, the description lands on one row and its rate on the next,
     * and every line silently loses its price. This is not hypothetical: it is
     * what a real photograph did.
     */
    /*
     * Words 15px apart, columns 300px apart, and a baseline that falls about
     * seven pixels per column — under the same-line tolerance step by step, but
     * thirty across the row, which is what breaks a rule measured from the
     * front of the line.
     */
    const w = (s: string, x: number, y: number) => cell(s, x, y, s.length * 18, 30)
    expect(cellsToRows([
      w('CRCA', 100, 450), w('SHEET', 187, 457), w('12', 700, 468), w('MT', 900, 480),
      w('INCOLOY', 100, 520), w('1000', 700, 538),
    ])).toEqual([['CRCA SHEET', '12', 'MT'], ['INCOLOY', '1000']])
  })

  it('leaves a square page exactly as it found it', () => {
    /*
     * The correction has to cost nothing when there is nothing to correct. A
     * PDF is square, so the estimate must come back at zero rather than at
     * whatever the last few runs happened to imply.
     */
    const w = (s: string, x: number, y: number) => cell(s, x, y, s.length * 18, 30)
    expect(cellsToRows([
      w('CRCA', 100, 450), w('SHEET', 187, 450), w('12', 700, 450),
      w('INCOLOY', 100, 520), w('1000', 700, 520),
    ])).toEqual([['CRCA SHEET', '12'], ['INCOLOY', '1000']])
  })

  it('and ignores a lean it has too little evidence for', () => {
    // two runs on a page is not a tilt, it is two runs
    const w = (s: string, x: number, y: number) => cell(s, x, y, 40, 10)
    expect(cellsToRows([w('a', 0, 100), w('b', 400, 140)])).toEqual([['a'], ['b']])
  })

  it('scales its tolerance to the type size, rather than a fixed gap', () => {
    // 5pt apart is one line in 14pt type and two lines in 6pt type. A constant
    // would have to be wrong about one of them.
    expect(cellsToRows([cell('A', 0, 100, 10, 14), cell('B', 50, 105, 10, 14)]))
      .toEqual([['A', 'B']])
    expect(cellsToRows([cell('A', 0, 100, 10, 6), cell('B', 50, 105, 10, 6)]))
      .toEqual([['A'], ['B']])
  })
})
