'use client'
import { useEffect, useMemo, useState } from 'react'
import { Dialog } from '@/components/ui/Dialog'
import { Field, TextInput } from '@/components/ui/Field'
import { Icon } from '@/components/ui/icons'
import { useWorkspace } from '@/components/workspace/store'
import { download } from '@/lib/sheet/csv'
import { canShareFile, mailtoUrl, shareFile, whatsappUrl, type Sendable } from '@/lib/paper/share'
import type { Problem } from '@/lib/paper/render'
import type { SendEntry } from '@/lib/workspace/types'

/**
 * A document, and four ways to hand it over.
 *
 * Written once for both things this build puts on paper. The preview is the
 * real generated bytes shown back, not a second rendering of the same layout —
 * so what is on screen is the file that will be sent, and there is no drift to
 * maintain between them.
 *
 * Every send button opens something the person then presses send in. §11 has
 * said since the first commit that the system never contacts a supplier, and
 * none of these do. What the app contributes is the paper, the message with the
 * figures already in it, and the record that you sent it — which is what makes
 * a week of silence visible afterwards.
 */
export interface Paper {
  /** null for an unaddressed copy, which only a request ever has */
  vendor: { id: string; name: string } | null
  problems: Problem[]
  /** materials with no quantity on them — not ready to hand over at all */
  blanks?: string[]
  fileName: string
  sendable: Sendable
  render: () => Promise<Blob>
  /**
   * Where the addressee's phone and email live, when that is not the supplier
   * book — a customer keeps their own on their record, and a number typed in
   * here is saved back there.
   */
  contact?: { phone?: string; email?: string }
  saveContact?: (field: 'phone' | 'email', value: string) => void
}

export function PaperDialog({ open, onClose, title, sub, papers, sentTo, onSent }: {
  open: boolean
  onClose: () => void
  title: string
  sub?: string
  papers: Paper[]
  /** supplier ids this document has already been handed to */
  sentTo: Set<string>
  onSent: (vendorId: string, via: SendEntry['via']) => void
}) {
  const { workspace, update } = useWorkspace()
  const [at, setAt] = useState(0)
  const [url, setUrl] = useState<string | null>(null)
  const [file, setFile] = useState<File | null>(null)
  const [busy, setBusy] = useState(true)
  const [failed, setFailed] = useState<string | null>(null)
  const [askContact, setAskContact] = useState<'phone' | 'email' | null>(null)
  const [draft, setDraft] = useState('')

  const paper: Paper | undefined = papers[at]
  const key = paper ? `${paper.fileName}` : ''

  /*
   * The bytes are built when the copy changes, and the blob URL is revoked when
   * it is replaced — not straight after assigning it, which blanks the frame in
   * Safari. Building here rather than in the click handler also matters:
   * `navigator.share` needs the user gesture still to be live, and awaiting a
   * third of a megabyte of jsPDF inside the handler loses it.
   */
  useEffect(() => {
    if (!open || !paper) return
    let alive = true
    let made: string | null = null
    setBusy(true); setFailed(null)
    paper.render().then((blob) => {
      if (!alive) return
      made = URL.createObjectURL(blob)
      setUrl(made)
      setFile(new File([blob], paper.fileName, { type: 'application/pdf' }))
      setBusy(false)
    }).catch((e) => {
      if (!alive) return
      setFailed((e as Error).message)
      setBusy(false)
    })
    return () => { alive = false; if (made) URL.revokeObjectURL(made) }
  }, [open, key]) // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { if (open) setAt(0) }, [open, title])

  if (!open || !workspace || !paper) return null
  const ws = workspace
  const contact = paper.saveContact ? paper.contact : paper.vendor ? ws.vendorContact[paper.vendor.id] : undefined

  const record = (via: SendEntry['via']) => {
    if (paper.vendor) onSent(paper.vendor.id, via)
  }

  const saveContact = () => {
    if (!paper.vendor || !askContact) return
    if (paper.saveContact) {
      paper.saveContact(askContact, draft.trim())
      setAskContact(null); setDraft('')
      return
    }
    const id = paper.vendor.id
    update((w) => ({
      ...w,
      vendorContact: { ...w.vendorContact, [id]: { ...w.vendorContact[id], [askContact]: draft.trim() } },
    }))
    setAskContact(null); setDraft('')
  }

  const openLink = (href: string, via: SendEntry['via']) => {
    window.open(href, '_blank', 'noopener')
    record(via)
  }

  return (
    <>
      <Dialog open onClose={onClose} wide title={title} sub={sub}>
        {papers.length > 1 && (
          <div className="flex flex-wrap gap-1.5 border-b border-line-soft px-4 py-2.5">
            {papers.map((d, i) => {
              const done = d.vendor ? sentTo.has(d.vendor.id) : false
              return (
                <button key={d.vendor?.id ?? i} type="button" onClick={() => setAt(i)}
                  className={`press inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-[12.5px] font-medium transition-colors ${
                    i === at ? 'bg-accent-ink text-on-accent' : 'border border-line bg-surface hover:bg-surface-2'}`}>
                  {done && <Icon name="check" className={`size-3 ${i === at ? '' : 'text-good'}`} />}
                  {d.vendor?.name ?? 'No supplier'}
                </button>
              )
            })}
          </div>
        )}

        <div className="px-4 py-4">
          {/*
            * A different kind of not-ready from the one below. Those are
            * characters the PDF cannot draw and the message carries fine; this
            * is a line with no quantity, which no way of sending fixes.
            */}
          {(paper.blanks?.length ?? 0) > 0 && (
            <div className="mb-3 rounded-lg border border-critical/30 bg-critical-soft px-3 py-2.5">
              <p className="text-[12.5px] font-medium">
                {paper.blanks!.length === 1
                  ? 'One line has no quantity on it'
                  : `${paper.blanks!.length} lines have no quantity on them`}
              </p>
              <p className="mt-1 text-[12px] leading-snug text-ink-2">
                {paper.blanks!.join(', ')}
              </p>
              <p className="mt-1.5 text-[11.5px] leading-snug text-ink-3">
                Nothing in your records said how much to buy — no request behind it,
                nothing short on the shelf, and no order size on the material. Put a
                quantity on the order before handing it over.
              </p>
            </div>
          )}

          {paper.problems.length > 0 && (
            <div className="mb-3 rounded-lg border border-warn/30 bg-warn-soft px-3 py-2.5">
              <p className="text-[12.5px] font-medium">Some of this cannot be printed</p>
              <ul className="mt-1 space-y-0.5">
                {paper.problems.map((p) => (
                  <li key={p.where} className="text-[12px] leading-snug text-ink-2">
                    {p.where} contains {p.chars.map((c) => `“${c}”`).join(', ')}
                  </li>
                ))}
              </ul>
              <p className="mt-1.5 text-[11.5px] leading-snug text-ink-3">
                Those characters will be missing from the PDF — it can only draw Latin letters.
                The WhatsApp and email messages carry them fine, so either send one of those, or
                write these fields in English as well.
              </p>
            </div>
          )}

          <Preview url={url} busy={busy} failed={failed} name={paper.fileName} />
        </div>

        <footer className="flex flex-wrap items-center gap-2 border-t border-line-soft px-4 py-3">
          <button type="button" onClick={onClose}
            className="press rounded-lg px-2.5 py-2 text-[13px] text-ink-2 hover:text-ink">Close</button>

          <span className="ml-auto flex flex-wrap items-center gap-2">
            {file && canShareFile(file) && (
              <Send icon="share" label="Share" onClick={async () => {
                const r = await shareFile(file, paper.sendable)
                // a cancel is not a send — recording one would make a document
                // look delivered when nobody was ever handed it
                if (r === 'shared') record('share')
              }} />
            )}

            <Send icon="whatsapp" label="WhatsApp" disabled={busy} onClick={() => {
              const href = whatsappUrl(paper.sendable, contact?.phone)
              if (!href) { setAskContact('phone'); setDraft(contact?.phone ?? ''); return }
              if (file) download(file.name, file)
              openLink(href, 'whatsapp')
            }} />

            <Send icon="mail" label="Email" disabled={busy} onClick={() => {
              if (!contact?.email) { setAskContact('email'); setDraft(''); return }
              if (file) download(file.name, file)
              openLink(mailtoUrl(paper.sendable, contact.email), 'email')
            }} />

            <Send icon="download" label="Download" primary disabled={busy || !file}
              onClick={() => { if (file) { download(file.name, file); record('download') } }} />
          </span>
        </footer>
      </Dialog>

      {askContact && paper.vendor && (
        <Dialog open onClose={() => setAskContact(null)}
          title={`${paper.vendor.name}’s ${askContact === 'phone' ? 'WhatsApp number' : 'email'}`}>
          <div className="space-y-3 px-4 py-4">
            <Field label={askContact === 'phone' ? 'Number' : 'Email address'}
              hint={askContact === 'phone'
                ? 'With the country code. It is kept against the supplier for next time.'
                : 'Kept against the supplier for next time.'}>
              <TextInput value={draft} onChange={setDraft} autoFocus onEnter={saveContact}
                placeholder={askContact === 'phone' ? '+91 98220 11234' : 'sales@supplier.in'} />
            </Field>
            <p className="text-[11.5px] leading-snug text-ink-3">
              This stays on this machine, like everything else here. Nothing is sent anywhere —
              the button opens {askContact === 'phone' ? 'WhatsApp' : 'your mail app'} and you
              press send.
            </p>
          </div>
          <footer className="flex items-center gap-2 border-t border-line-soft px-4 py-3">
            <button type="button" onClick={() => setAskContact(null)}
              className="press rounded-lg px-2.5 py-2 text-[13px] text-ink-2 hover:text-ink">Cancel</button>
            <span className="ml-auto" />
            <button type="button" onClick={saveContact} disabled={draft.trim() === ''}
              className="press rounded-lg border border-accent-ink bg-accent-ink px-3.5 py-2 text-[13px] font-semibold text-on-accent hover:bg-accent disabled:opacity-40">
              Save it
            </button>
          </footer>
        </Dialog>
      )}
    </>
  )
}

/**
 * The generated file, shown back.
 *
 * An `<iframe>` of a blob PDF does not render on iOS Safari and historically
 * downloaded rather than displayed on Android, and this build is phone-first —
 * so narrow screens get a button that opens it in whatever the phone uses for
 * PDFs instead of a frame that would be blank.
 */
function Preview({ url, busy, failed, name }: {
  url: string | null
  busy: boolean
  failed: string | null
  name: string
}) {
  const [wide, setWide] = useState(true)
  useEffect(() => {
    const check = () => setWide(window.matchMedia('(min-width: 640px)').matches)
    check()
    window.addEventListener('resize', check)
    return () => window.removeEventListener('resize', check)
  }, [])

  if (failed) {
    return (
      <p className="rounded-lg border border-critical/30 bg-critical-soft px-3 py-2.5 text-[12.5px] text-ink-2">
        The document could not be built: {failed}
      </p>
    )
  }
  if (busy || !url) {
    return (
      <div className="grid h-[22rem] place-items-center rounded-lg border border-line bg-surface-2">
        <span className="text-[12.5px] text-ink-3">Building the document…</span>
      </div>
    )
  }
  if (!wide) {
    return (
      <a href={url} target="_blank" rel="noopener"
        className="press flex items-center justify-center gap-2 rounded-lg border border-line bg-surface-2 px-4 py-8 text-[13px] font-medium">
        <Icon name="doc" className="size-4 text-ink-3" />
        Open {name}
      </a>
    )
  }
  return (
    <iframe src={url} title="The document"
      className="h-[26rem] w-full rounded-lg border border-line bg-surface-2" />
  )
}

function Send({ icon, label, onClick, primary, disabled }: {
  icon: 'share' | 'whatsapp' | 'mail' | 'download'
  label: string
  onClick: () => void
  primary?: boolean
  disabled?: boolean
}) {
  return (
    <button type="button" onClick={onClick} disabled={disabled}
      className={`press inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-[13px] font-medium transition-colors disabled:opacity-40 ${
        primary
          ? 'border border-accent-ink bg-accent-ink font-semibold text-on-accent hover:bg-accent'
          : 'border border-line bg-surface hover:bg-surface-2'}`}>
      <Icon name={icon} className="size-3.5" />
      {label}
    </button>
  )
}

/**
 * What a send log says about one document.
 *
 * Exported because both lists want it: "sent to 2 · nothing back in 6 days" on
 * a request, and the same shape on an order. Whatever `useMemo` it looks like
 * it needs, it is a filter over a list that is never long.
 */
export function useSentTo(kind: SendEntry['kind'], id: string): SendEntry[] {
  const { workspace } = useWorkspace()
  return useMemo(
    () => (workspace?.sendLog ?? []).filter((s) => s.kind === kind && s.id === id),
    [workspace, kind, id],
  )
}
